#ifndef INCLUDE_CCAPI_CPP_CCAPI_ENABLE_EXCHANGE_H_
#define INCLUDE_CCAPI_CPP_CCAPI_ENABLE_EXCHANGE_H_
#ifdef ENABLE_ALL_EXCHANGE
#ifndef ENABLE_COINBASE
#define ENABLE_COINBASE
#endif
#ifndef ENABLE_GEMINI
#define ENABLE_GEMINI
#endif
#ifndef ENABLE_KRAKEN
#define ENABLE_KRAKEN
#endif
#ifndef ENABLE_BITSTAMP
#define ENABLE_BITSTAMP
#endif
#ifndef ENABLE_BITFINEX
#define ENABLE_BITFINEX
#endif
#ifndef ENABLE_BITMEX
#define ENABLE_BITMEX
#endif
#ifndef ENABLE_BINANCE_US
#define ENABLE_BINANCE_US
#endif
#endif
#endif  // INCLUDE_CCAPI_CPP_CCAPI_ENABLE_EXCHANGE_H_
